config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :events do
    resources :surveys, except: [:edit, :update]
    resources :papers do
      resources :comments
      resources :reviews
      resources :assingments
      resources :classrooms
    end
  end

  resources :users, except: [:create, :show]

  post 'create_user' => 'users#create', as: :create_user
  get '/documents' => 'papers#list_all'
  get '/my_documents' => 'papers#my_documents'
  get '/assigned_tutor' => 'papers#list_assigned_tutor'
  get '/assigned_relator' => 'papers#list_assigned_relator'
  get '/users/change_password' => 'users#change_password'
  post '/users/update_password' => 'users#update_password'
  get '/events/:event_id/papers/:id/edit_status' => 'papers#edit_status'
  patch '/events/:event_id/papers/:id' => 'papers#update_status'   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/paper.rb
class Paper < ApplicationRecord
    has_many :comments
    has_many :reviews
    
    belongs_to :user
    alias_attribute :author, :user
    
    belongs_to :event
    
    has_one :assingment
    has_one :classroom
    
    has_one_attached :pdf_file
    acts_as_taggable

    # paginates_per 6

    after_update :send_notification

    def send_notification
        PaperMailer.status_notification(self.user, self, self.event).deliver
    end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  load_and_authorize_resource :event
  load_and_authorize_resource :paper, through: :event, except: [:list_all, :list_assigned_tutor, :list_assigned_relator, :my_documents]

  # GET /papers
  # GET /papers.json
  def index
    @event = Event.find(params[:event_id])
    @papers = @event.papers.page(params[:page]).per(6)
    @papers_by_user = @papers.where(:user_id => current_user.id)
  end
  
  # GET /papers/1
  # GET /papers/1.json
  def show
    @event = Event.find(params[:event_id])
    @paper = @event.papers.find(params[:id])
    @assingment = @paper.assingment
    @classroom = @paper.classroom
    respond_to do |format|
      format.html
      format.pdf { render template: 'papers/acta', pdf: 'Acta UCB', layout: 'acta.html' }
    end
  end

  # GET /papers/new
  def new
    @event = Event.find(params[:event_id])
    @paper = @event.papers.new
  end

  # GET /papers/1/edit
  def edit
    @event = Event.find(params[:event_id])
    @paper = @event.papers.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @event = Event.find(params[:event_id])
    @paper = @event.papers.new(paper_params)
    @paper.status = 'en proceso'

    # respond_to do |format|
      if @paper.save
        redirect_to event_papers_path(@event)
        # format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        # format.json { render :show, status: :created, location: @paper }
      else
        render 'new'
        # format.html { render :new }
        # format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    # end
  end

  def edit_status
    edit()
  end

  def update_status
    @event = Event.find(params[:event_id])
    @paper = @event.papers.find(params[:id])
    
    if (@paper.update_attribute(:status => params[:paper][:status]))
      redirect_to event_papers_path(@event)
     else
      redirect_to '/events/'+ @event.id.to_s + '/papers/' + @paper.id.to_s + '/edit_status'
     end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    @event = Event.find(params[:event_id])
    @paper = @event.papers.find(params[:id])
    @paper.status = 'en proceso'
    # respond_to do |format|
      if @paper.update(paper_params)
        redirect_to event_papers_path(@event)
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    # end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def list_all
    @papers = Paper.all.page(params[:page]).per(6)
  end

  def my_documents
    @papers = current_user.papers
  end

  def list_assigned_tutor
    @papers = Paper.all.page(params[:page]).per(8)
  end

  def list_assigned_relator
    @papers = Paper.all.page(params[:page]).per(8)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:title, :resume, :general_purpose, :specific_purpose, :problem_definition, :tag_list, :pdf_file, :user_id, :google_docs_link, :status, :doc_type)
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_admin_options.html.erb
<table>
  <thead class="header-row">
    <tr>
      <th>No.</th>
      <th>Título</th>
      <th>Estudiante</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
      <% @papers.each_with_index do |paper, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= link_to paper.title, event_paper_path(@event, paper), class: 'link-to-text' %></td>
          <td><%= paper.user.name %> <%= paper.user.lastname %></td>
          <% if paper.classroom.present? && paper.assingment.present? %>
            <td>
                <%= link_to event_paper_path(@event, paper, :format => :pdf), class: "btn-small btn-floating grey", target: "_blank" do %>
                    em> class="material-icons tooltipped" data-position='bottom' data-tooltip='Generar Acta'>insert_drive_file</em>
                <% end %>
            </td>
          <% end %>
          <td>
            <%= link_to '/events/'+ @event.id.to_s + '/papers/'+ paper.id.to_s + '/edit_status', 
                class: 'waves-effect btn-floating btn-small grey' do %>
                    <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Cambiar Estado'>swap_horiz</em>
            <%end%>
          </td>
          <% if @event.survey.present? && paper.assingment.present? %>
            <% if paper.reviews.find_by(paper_id: paper.id) %>
                <td>
                    <%= link_to event_paper_reviews_path(@event, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver Revisiones'>search</em>
                    <% end %>
                </td>
            <% end %>
            <% if paper.reviews.find_by(user_id: current_user.id) %>
                <td>
                    <%= link_to edit_event_paper_review_path(@event, paper, paper.reviews.find_by(user_id: current_user.id)), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Revisión'>edit</em>
                    <% end %>
                </td>
            <% else%>
                <td>
                    <%= link_to new_event_paper_review_path(@event, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Realizar Revisión'>add_box</em>
                    <% end %>
                </td>
            <%end%>
          <% end %>
          <td>
                <% if paper.assingment.present? %>
                    <%= link_to edit_event_paper_assingment_path(@event, paper, paper.assingment), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Tribunal'>group</em>
                    <% end %>
                <% else %>
                    <%= link_to new_event_paper_assingment_path(@event, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Asignar Tribunal'>group_add</em>
                    <% end %>
                <% end %>
          </td>
          <td>
            <% if paper.classroom.present? %>
                <%= link_to edit_event_paper_classroom_path(@event, paper, paper.classroom), class: "waves-effect btn-floating btn-small grey" do %>
                    <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Aula'>event_available</em>
                <% end %>
            <% else %>
                <%= link_to new_event_paper_classroom_path(@event, paper, paper.classroom), class: "waves-effect btn-floating btn-small grey" do %>
                    <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Asignar Aula'>event</em>
                <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

<%= paginate @papers %>

app/views/papers/_director_options.html.erb
<table>
  <thead class="header-row">
    <tr>
      <th>No.</th>
      <th>Título</th>
      <th>Estudiante</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
      <% @papers.each_with_index do |paper, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= link_to paper.title, event_paper_path(@event, paper), class: 'link-to-text' %></td>
          <td><%= paper.user.name %> <%= paper.user.lastname %></td>
          <td>
            <%= link_to rails_blob_path(paper.pdf_file, disposition: "inline"), 
                class: "waves-effect btn-floating btn-small grey", target: "_blank" do %>
                    <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver PDF'>visibility</<em
            <%end%>
          </td>
          <% if @event.survey.present? && paper.assingment.present? %>
            <% if paper.reviews.find_by(paper_id: paper.id) %>
              <td>
                <%= link_to event_paper_reviews_path(@event, paper), class: "waves-effect btn-floating btn-small grey" do %>
                  <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver Revisiones'>search</em>
                <% end %>
              </td>
            <% end %>
            <% if paper.reviews.find_by(user_id: current_user.id) %>
                <td>
                    <%= link_to edit_event_paper_review_path(@event, paper, paper.reviews.find_by(user_id: current_user.id)), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Revisión'>edit</em>
                    <% end %>
                </td>
            <% else%>
                <td>
                    <%= link_to new_event_paper_review_path(@event, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Realizar Revisión'>add_box</em>
                    <% end %>
                </td>
            <%end%>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>

<%= paginate @papers %>

app/views/papers/_editform.html.erb
<div class="row">
  <div class="col s12 m8 offset-m2">
    <div class="card brown lighten-5">
      <div class="card-content">
        <%= form_for([@event, @paper]) do |form| %>
          <h4 class="align center">Editar Registro Documento</h4><br>
          <% if @paper.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

              <ul>
              <% paper.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="input-field col s12">
            <%= form.label :doc_type, 'Tipo de documento *', class: 'active' %>
            <%= form.select :doc_type, ['Proyecto de Grado','Tesis de Grado','Pasantía','Trabajo Dirigido'] %>
          </div>
          <div class="input-field col s12">
            <%= form.label :title, 'Título *', class: "active" %>
            <%= form.text_area :title, class: "materialize-textarea" %>
          </div>
          <div class="input-field col s12">
            <%= form.label :google_docs_link, 'Link archivo Google Docs *' %>
            <%= form.text_field :google_docs_link, class: 'validate' %>
          </div>
          <div class="file-field input-field col s12">
            <div class="btn blue lighten-2">
              <span><em class="material-icons white-text">picture_as_pdf</em></span>
              <%= form.file_field :pdf_file, {accept: "application/pdf" } %>
            </div>
            <div class="file-path-wrapper">
              <%= text_field_tag nil, (form.object.pdf_file.filename), {id: nil, class: 'file-path validate'} %>
            </div>
          </div>
          <div class="input-field col s12">
            <%= form.label :resume, 'Resumen o Introducción', class: "active" %>
            <%= form.text_area :resume, :class => 'materialize-textarea' %>
          </div><br>

          <%= form.hidden_field :user_id, value: current_user.id %>

          <div class="col s12">
            <p class="required-alert">Los campos marcados con * son obligatorios.</p><br>
          </div>

          <div class="center-align">
              <%= button_tag(class: "btn-small waves-effect waves-light") do %>
                Editar
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/papers/_form.html.erb
<div class="row">
  <div class="col s12 m8 offset-m2">
    <div class="card-panel brown lighten-5">
      <div class="row valign-wrapper">
        <div class="col s12">
          <h4 class="align center">
            <em class="material-icons prefix">note_add</em>
            Nuevo Documento
          </h4><br>


          <%= form_for([@event, @paper]) do |form| %>
            <div class="input-field col s12">
              <%= form.label :doc_type, 'Tipo de documento *', class: 'active' %>
              <%= form.select :doc_type, ['Proyecto de Grado','Tesis de Grado','Pasantía','Trabajo Dirigido'], include_blank: 'Elija su tipo de documento' %>
            </div>
            <div class="input-field col s12">
              <%= form.label :title, 'Título *' %>
              <%= form.text_area :title, class: "materialize-textarea" %>
            </div>
            <div class="input-field col s12">
              <%= form.label :google_docs_link, 'Link archivo Google Docs *' %>
              <%= form.text_field :google_docs_link, class: 'validate' %>
            </div>
            <div class="file-field input-field col s12">
              <div class="btn blue lighten-2">
                <span><em class="material-icons">picture_as_pdf</em></span>
                <%= form.file_field :pdf_file, {accept: "application/pdf" } %>
              </div>
              <div class="file-path-wrapper">
                <input type="text" class="file-path validate" placeholder="Elija un archivo *">
              </div>
            </div>
            <div class="input-field col s12">
              <%= form.label :resume, 'Resumen o Introducción' %>
              <%= form.text_area :resume, :class => 'materialize-textarea' %>
            </div><br>

            <%= form.hidden_field :user_id, value: current_user.id %>

            <div class="col s12">
              <p class="required-alert">Los campos marcados con * son obligatorios.</p><br>
            </div>

            <% if Date.today <= @event.limit_date %>
              <div class="center-align">
                <%= button_tag(class: "btn-small waves-effect waves-light") do %>
                  Registrar
                <% end %>
              </div>
            <%end%>  
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<br><br><br>

app/views/papers/_student_options.html.erb
<% if Date.today <= @event.limit_date %>
  <p class="yellow lighten-3 right"><em class="material-icons">announcement</em> Fecha límite para subir documentos: <strong class="red-text"> <%= l(@event.limit_date, format: :long) %></strong></p><br><br><br>
  <%= link_to new_event_paper_path, class: "btn-small waves-effect right" do %>
    <em class="material-icons left">add</em>
    Añadir
  <% end %><br><br>
<% end %>

<table>
  <thead class="header-row">
    <tr>
      <th>No.</th>
      <th>Título</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @papers_by_user.each_with_index do |paper, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td class="title-row"><%= link_to paper.title, event_paper_path(@event, paper), class: 'link-to-text' %></td>
          <td>
            <%= link_to rails_blob_path(paper.pdf_file, disposition: "inline"), 
                class: "waves-effect btn-floating btn-small grey", target: "_blank" do %>
                <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver PDF'>visibility</em>
            <%end%>
          </td>
          <%if paper.status != 'en proceso'%>
            <td>
              <%= link_to event_paper_reviews_path(@event, paper), class: "waves-effect btn-floating btn-small grey" do %>
                <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver Revisiones'>search</em>
              <% end %>
            </td>
          <%end%>
          <td><%= link_to edit_event_paper_path(@event, paper), class: 'waves-effect btn-floating btn-small grey' do %>
            <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Documento'>edit</em>
            <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/papers/_submission.html.erb
<h5>Presentación</h5>
<div class="row flex">
    <div class="col s2 fr"><strong>Documento:</strong></div>
    <div class="col s10 fr"><%= paper.title %></div>
    <div class="col s2 sr"><strong>Autor:</strong></div>
    <div class="col s10 sr"><%= paper.user.complete_name %></div>
    <div class="col s2 fr"><strong>Archivos:</strong></div>
    <div class="col s10 fr">
        <%= link_to rails_blob_path(paper.pdf_file, disposition: "inline"), 
        class: "btn-flat pdf-sm", target: "_blank" do %>
         <em class="material-icons tooltipped" data-position='right' data-tooltip='Descargar PDF'>picture_as_pdf</em>
       <%end%>
    </div>
</div>

app/views/papers/acta.pdf.erb
<table>
    <tr>
        <td><%= wicked_pdf_image_tag "logo_ucb.jpg", width: "90", height: "140" %></td>
        <td><div class="row centro"><strong>universidad  católica  boliviana  "san  pablo" <br>Carrera de <%= @event.career %></strong></div></td>
    </tr>
</table><br>

<div class="defensa"><strong>Acta de <%= @event.name %></strong></div>

<div class="parrafo">
    <p>
        En acto académico realizado en la ciudad de Cochabamba, en fecha <strong><%= l(@classroom.defense_date, :format => :long) %>,</strong> 
        a horas <strong><%= @classroom.defense_hour.strftime("%k:%M") %>,</strong> se reunió el tribunal examinador del Trabajo de Grado del (de la) estudiante 
        <strong><%= @paper.user.name %> <%= @paper.user.lastname %>,</strong> conformado por <strong><%= User.find(@assingment.tutor_id).professional_degree %> <%= User.find(@assingment.tutor_id).name %> <%= User.find(@assingment.tutor_id).lastname %></strong> como profesor(a) Guía, 
        <strong><%= User.find(@assingment.relator_id).professional_degree %> <%= User.find(@assingment.relator_id).name %> <%= User.find(@assingment.relator_id).lastname %></strong> como profesor(a) Relator(a) y <strong><%= User.find(@assingment.director_id).professional_degree %> <%= User.find(@assingment.director_id).name %> <%= User.find(@assingment.director_id).lastname %></strong> como 
        presidente del Tribunal. <br><br>
        Luego de escuchar y evaluar el informe, que lleva por título: "<strong><%= @paper.title %></strong>" 
        y está inscrito en la modalidad de <%=@paper.doc_type%> el tribunal decidió 
        ________________ el trabajo y otorgar la calificación de ______ (________________________________). 
        Asimismo, el tribunal consensuó las siguientes observaciones y recomendaciones, que deben ser 
        atendidas para las fases siguientes del proceso de titulación: <br><br>
        1. _________________________________________________________________________________________ <br>
        2. _________________________________________________________________________________________ <br>
        3. _________________________________________________________________________________________ <br>
        4. _________________________________________________________________________________________ <br>
        5. _________________________________________________________________________________________ <br>
        6. _________________________________________________________________________________________ <br>
        7. _________________________________________________________________________________________ <br>
        8. _________________________________________________________________________________________ <br>
    </p>
    <br><br><br>
    <table class="trib">
        <tr>
            <td>__________________________<br> Profesor(a) Guía</td>
            <td>__________________________<br> Profesor(a) Relator</td>
        </tr>
        <tr class="firma">
            <td>_______________________________<br> Presidente del Tribunal</td>
            <td>__________________________<br> Docente de la Materia</td>
        </tr>
    </table>
    <table class="est">
        <tr><td>__________________________<br> Estudiante</td></tr>
    </table>
</div>

app/views/papers/edit_status.html.erb
<div class="row">
    <div class="col s10 m6 offset-m3">
        <div class="card brown lighten-5">
            <div class="card-content">
                <h4 class="center-align">Cambiar estado</h4>
                <%= form_for([@event, @paper]) do |f| %>
                    <div class="row">
                        <div class="input-field col s6 offset-m3">
                            <%= f.label :status, 'Estado *' %><br>
                            <%= f.select :status, ['revisado', 'aceptado','rechazado'] %>
                        </div>
                    </div>

                    <div class="center-align">
                        <%= button_tag(class: "btn-small waves-effect waves-light") do %>
                            Cambiar
                        <% end %>
                        </div>
                <% end %>
            
            </div>
        </div>
    </div>
</div>

app/views/papers/index.html.erb
<h3 class="align center">Documentos</h3>

<% if current_user.estudiante? %>
  <%= render partial: 'student_options', object: @papers_by_user %>
<%end%>

<% if current_user.professor_role? || current_user.admin_role? %>
  <%= render partial: 'admin_options', object: @papers %>
<% elsif current_user.docente? %>
  <%= render partial: 'professors_options', object: @papers %>
<% elsif current_user.director? %>
  <%= render partial: 'director_options', object: @papers %>
<% end %>

app/views/papers/list_all.html.erb
<h3 class="align center">Documentos</h3>

<table>
  <thead class="header-row">
    <tr>
      <th>No.</th>
      <th>Título</th>
      <th>Estudiante</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each_with_index do |paper, index| %>
      <% if current_user.career == paper.user.career %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= link_to paper.title, event_paper_path(paper.event_id, paper), class: 'link-to-text' %></td>
          <td><%= paper.user.name %> <%= paper.user.lastname %></td>
          <% if paper.assingment.present? %>
            <% if paper.reviews.find_by(paper_id: paper.id) %>
              <td>
                <%= link_to event_paper_reviews_path(paper.event_id, paper), class: "waves-effect btn-floating btn-small grey" do %>
                  <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver Revisiones'>search</em>
                <% end %>
              </td>
            <% end %>
            <% if paper.reviews.find_by(user_id: current_user.id) %>
                <td>
                    <%= link_to edit_event_paper_review_path(paper.event_id, paper, paper.reviews.find_by(user_id: current_user.id)), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Revisión'>edit</em>
                    <% end %>
                </td>
            <% else%>
                <td>
                    <%= link_to new_event_paper_review_path(paper.event_id, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Realizar Revisión'>add_box</em>
                    <% end %>
                </td>
            <%end%>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= paginate @papers %>

app/views/papers/list_assigned_relator.html.erb
<h3 class="align center">Documentos</h3><br>

<table>
  <thead class="header-row">
    <tr>
      <th>No.</th>
      <th>Título</th>
      <th>Estudiante</th>
      <th>Carrera</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each_with_index do |paper, index| %>
        <% if paper.assingment.present? %>
            <% if current_user.id == paper.assingment.relator_id %>
                <tr>
                  <td><%= index+1 %></td>
                  <td class="title-assigned"><%= link_to paper.title, event_paper_path(paper.event_id, paper), class: 'link-to-text' %></td>
                  <td><%= paper.user.name %> <%= paper.user.lastname %></td>
                  <td><%= paper.user.career %></td>
                  <% if paper.reviews.find_by(paper_id: paper.id) %>
                    <td>
                      <%= link_to event_paper_reviews_path(paper.event_id, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver Revisiones'>search</em>
                      <% end %>
                    </td>
                  <% end %>
                  <% if paper.reviews.find_by(user_id: current_user.id) %>
                    <td>
                      <%= link_to edit_event_paper_review_path(paper.event_id, paper, paper.reviews.find_by(user_id: current_user.id)), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Revisión'>edit</em>
                      <% end %>
                    </td>
                  <% else%>
                    <td>
                      <%= link_to new_event_paper_review_path(paper.event_id, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Realizar Revisión'>add_box</em>
                      <% end %>
                    </td>
                  <%end%>
                </tr>
            <% end %>
          <% end %>
      <% end %>
  </tbody>
</table>

<%= paginate @papers %>

app/views/papers/list_assigned_tutor.html.erb
<h3 class="align center">Documentos</h3><br>

<table>
  <thead class="header-row">
    <tr>
      <th>No.</th>
      <th>Título</th>
      <th>Estudiante</th>
      <th>Carrera</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each_with_index do |paper, index| %>
        <% if paper.assingment.present? %>
            <% if current_user.id == paper.assingment.tutor_id %>
                <tr>
                  <td><%= index+1 %></td>
                  <td class="title-assigned"><%= link_to paper.title, event_paper_path(paper.event_id, paper), class: 'link-to-text' %></td>
                  <td><%= paper.user.name %> <%= paper.user.lastname %></td>
                  <td><%= paper.user.career %></td>
                  <% if paper.reviews.find_by(paper_id: paper.id) %>
                    <td>
                      <%= link_to event_paper_reviews_path(paper.event_id, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Ver Revisiones'>search</em>
                      <% end %>
                    </td>
                  <% end %>
                  <% if paper.reviews.find_by(user_id: current_user.id) %>
                    <td>
                      <%= link_to edit_event_paper_review_path(paper.event_id, paper, paper.reviews.find_by(user_id: current_user.id)), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Editar Revisión'>edit</em>
                      <% end %>
                    </td>
                  <% else%>
                    <td>
                      <%= link_to new_event_paper_review_path(paper.event_id, paper), class: "waves-effect btn-floating btn-small grey" do %>
                        <em class="material-icons tooltipped" data-position='bottom' data-tooltip='Realizar Revisión'>add_box</em>
                      <% end %>
                    </td>
                  <%end%>
                </tr>
            <% end %>
          <% end %>
      <% end %>
  </tbody>
</table>

<%= paginate @papers %>

app/views/papers/new.html.erb
<%= render 'form' %>