config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :events do
    resources :surveys, except: [:edit, :update]
    resources :papers do
      resources :comments
      resources :reviews
      resources :assingments
      resources :classrooms
    end
  end

  resources :users, except: [:create, :show]

  post 'create_user' => 'users#create', as: :create_user
  get '/documents' => 'papers#list_all'
  get '/my_documents' => 'papers#my_documents'
  get '/assigned_tutor' => 'papers#list_assigned_tutor'
  get '/assigned_relator' => 'papers#list_assigned_relator'
  get '/users/change_password' => 'users#change_password'
  post '/users/update_password' => 'users#update_password'
  get '/events/:event_id/papers/:id/edit_status' => 'papers#edit_status'
  patch '/events/:event_id/papers/:id' => 'papers#update_status'   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :reviews
    belongs_to :event
    
    accepts_nested_attributes_for :questions, allow_destroy: true

    validates_presence_of :name
    validates_associated :questions
    validate :at_least_one_question
    validate :maximum_score_is_hundred

    def quantitative_questions
        questions.select { |question| question.is_quantitative? }
    end
    
    def maximum_score
        quantitative_questions.map{ |question| question.max_score }.sum
    end

    def safe_to_remove?
        reviews.count == 0
    end

    private 

    def at_least_one_question
        errors.add(:questions, "should be at least 1") if questions.size < 1
    end

    def maximum_score_is_hundred
        errors.add(:questions, "maximum scores should sum 100") if maximum_score != 100
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
    load_and_authorize_resource :event
    load_and_authorize_resource :survey, through: :event, singleton: true

    def show
        @event = Event.find(params[:event_id])
        @survey = Survey.find(params[:id])
    end

    def new
        @event = Event.find(params[:event_id])
        @survey = @event.build_survey
        @survey.questions.build(type: Question.default_type)
    end

    def create
        @event = Event.find(params[:event_id])
        @survey = @event.create_survey(survey_params)
        if @survey.save
            redirect_to events_path
        else
            render :new
        end
    end

    def destroy
        @survey = Survey.find(params[:id]).destroy
        redirect_to events_path
    end

    private
    def survey_params
        params.require(:survey).permit(:name, :event_id,
            questions_attributes: [:id, :title, :description, :type, :max_score, :_destroy,
                options_attributes: [:id, :point, :description, :_destroy]])
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<div class="col s12 m8 offset-m2 l6 offset-l3">
  <div class="card-panel grey lighten-5 z-depth-1">
    <div class="row valign-wrapper">
      <div id='survey' class="col s12">
        <%= form_for([@event, @survey]) do |survey_form| %>
          <div class="row">
            <div class="col s12 m8 offset-m2">
              <div class="z-depth-0 card-panel green lighten-5">
                <div class="center-align">
                  <em class="inline-icon tiny material-icons">info_outline</em> <span class="grey-text text-darken-3">La suma de los puntajes máximos debe ser 100</span>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="input-field col s12">
                <%= survey_form.label :name, 'Título *' %>
                <%= survey_form.text_field :name, type: "text", class: "validate" %>
            </div>
          </div>
          <%= survey_form.fields_for :questions do |question_form| %>
            <%= render "question_fields", f: question_form %>
          <% end %>

          <div>
            <% question_types_info.each do |display_name, type| %>
              <%= link_to_add_association "Añadir sección #{display_name}", survey_form, :questions,
                wrap_object: Proc.new { |question| quesion = question.becomes!(type); question } %> |
            <% end %>
          </div><br>
          <div>
            <p class="required-alert">Los campos marcados con * son obligatorios.</p>
          </div>
          <div class="center-align">
            <%= link_to 'Crear Formulario', '#confirmation-modal', class: 'modal-trigger btn-small waves-effect waves-light' %>
          </div>
          <div id="confirmation-modal" class="modal">
            <div class="modal-content">
              <h4>Confirmación</h4>
              <p>Una vez creado el formulario, los usuarios podrán registrar revisiones, debido a esto, este formulario no se podrá modificar.</p>
              <p>¿Deseas guardar el formulario?</p>
            </div>
            <div class="modal-footer">
              <%= link_to 'Cancelar', '#confirmation-modal', class: 'modal-close btn-small btn-flat' %>
              <%= survey_form.submit 'Crear Formulario', class: 'text-white btn-small' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/surveys/_option_fields.html.erb
<div class="option_fields">
    <div class="row">
        <div class="input-field col s2">
            <%= f.label :point, "Valor *" %>
            <%= f.number_field :point %>
        </div>
        <div class="input-field col s8">
            <%= f.label :description, "Descripción *" %>
            <%= f.text_field :description, type: "text", class: "validate" %>
        </div>
        <div class="input-field col s2">
            <%= f.hidden_field :_destroy %>
            <%= link_to_remove_association button_tag(raw("<i class='material-icons'>close</i>"), type:'button', class: "btn-small red lighten-3 waves-effect"), f, { wrapper_class:'option_fields'} %>
        </div>
    </div>
</div>

app/views/surveys/_question_fields.html.erb
<div class="question_fields">
    <div class="card-panel brown lighten-5 z-depth-1">
        <div class="row">
            <% question = f.object %>
            <div class="input-field col s2 question_type">
                <%= f.label :type, "Tipo de revisión", class: "active" %>
                <%= f.hidden_field :type%>
                <%= content_tag :p, question.display_type, class:'question_type' %>
                <%= f.hidden_field :_destroy %>
                <%= link_to_remove_association content_tag(:p, 'Quitar Sección', class:'red-text'), f, { wrapper_class: 'question_fields' } %>
            </div>
            <div class="input-field col s8">
                <%= f.label :title, "Sección *", class: 'active' %>
                <%= f.text_field :title, placeholder: 'Ingrese la sección a revisar del documento. Ejemplo: Antecedentes', type: "text", class: "validate" %>
            </div>
            <% if question.display_type=='Escala' %>
                <div class="input-field col s2">
                    <%= f.label :max_score, 'Puntaje máximo *' %>
                    <%= f.number_field :max_score, class: :text_field, step: :any %>
                </div>
            <% end %>
        </div>
        <%= render fields_of_question(question.type), f: f %>
    </div>
</div>

app/views/surveys/index.html.erb
<h3 class="align center">Revisiones</h3>

<%= link_to new_event_survey_path, class: "btn-small waves-effect right" do %>
    <em class="material-icons left">add</em>Crear
<% end %>
    
<table>
    <thead>
        <tr>
            <th>Título</th>
        </tr>
    </thead>
    <tbody>
        <% @surveys.each do |survey| %>
            <tr>
                <td><%= survey.name %></td>
                <td><%= link_to "Ver", event_survey_path(@event, survey) %></td>
                <td><%= link_to "Editar", edit_event_survey_path(@event, survey) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/surveys/new.html.erb
<h3 class="align center">Nuevo Formulario de Revisión</h3>
<%= render 'form' %>

app/views/surveys/show.html.erb
<div class="col s12 m8 offset-m2 l6 offset-l3">
  <div class="card-panel grey lighten-5 z-depth-1">
    <div class="row valign-wrapper">
      <div id='survey' class="col s12">
        <div class="row">
            <h5 class="center-align"><%= @survey.name %></h3>
        </div>
        <div class="row">
            <div class="col s12 m10 offset-m1">
                <% @survey.questions.each do |question| %>
                    <div class="center-align"> * * * </div>
                    <div class="section">
                        <strong><%= question.title %></strong>
                        <% if question.type == 'Questions::SelectOption' %>
                            <% question.options.each do |option|%>
                                <p><label>
                                    <%= radio_button_tag :score, option.value, false, disabled: true %>
                                    <span><%= option.show %></span>
                                </label></p>
                            <% end %>
                        <% elsif question.type == 'Questions::Text' %>
                            <p><%= question.description %></p>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
        <% if @survey.safe_to_remove? %> 
            <div class="row">
                <div class="col s3 push-s9">
                    <%= link_to raw("<i class='material-icons left'>delete</i>" + 'Eliminar'), event_survey_path(@survey), { method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'red-text'} %>
                </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>