config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :events do
    resources :surveys, except: [:edit, :update]
    resources :papers do
      resources :comments
      resources :reviews
      resources :assingments
      resources :classrooms
    end
  end

  resources :users, except: [:create, :show]

  post 'create_user' => 'users#create', as: :create_user
  get '/documents' => 'papers#list_all'
  get '/my_documents' => 'papers#my_documents'
  get '/assigned_tutor' => 'papers#list_assigned_tutor'
  get '/assigned_relator' => 'papers#list_assigned_relator'
  get '/users/change_password' => 'users#change_password'
  post '/users/update_password' => 'users#update_password'
  get '/events/:event_id/papers/:id/edit_status' => 'papers#edit_status'
  patch '/events/:event_id/papers/:id' => 'papers#update_status'   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      can :manage, Review, user_id: user.id
      can :read, [Event, Paper, Review]
      can [:change_password, :update_password], User

      can :manage, User if user.director?
      can :manage, Paper, user_id: user.id if user.estudiante?

      if user.professor_role? or user.admin_role?
        can :manage, [Event, Paper, Survey, Assingment, Classroom]
      end
    end

    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/assingment.rb
class Assingment < ApplicationRecord
  belongs_to :paper
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    belongs_to :paper
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :paper, counter_cache: true
  belongs_to :user
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :review
  belongs_to :question

  def is_quantitative?
    score
  end
  
  def is_qualitative?
    description
  end
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :papers
    has_one :survey

    validates_presence_of :name
end

app/models/option.rb
class Option < ApplicationRecord
    belongs_to :question

    validates_presence_of :point, :description

    def show
        "(#{point}) #{description}"
    end

    def value
        point
    end
end

app/models/paper.rb
class Paper < ApplicationRecord
    has_many :comments
    has_many :reviews
    
    belongs_to :user
    alias_attribute :author, :user
    
    belongs_to :event
    
    has_one :assingment
    has_one :classroom
    
    has_one_attached :pdf_file
    acts_as_taggable

    # paginates_per 6

    after_update :send_notification

    def send_notification
        PaperMailer.status_notification(self.user, self, self.event).deliver
    end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :options, dependent: :destroy
  has_many :evaluations, dependent: :destroy
  
  accepts_nested_attributes_for :options, allow_destroy: true
  validates_associated :options

  validates_presence_of :type, :title

  def self.default_type
    'Questions::SelectOption'
  end

  def display_type
    type ? type.constantize.display_type : 'Type not set'
  end

  def is_quantitative?
    max_score
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :paper
  belongs_to :user
  belongs_to :survey
  has_many :evaluations, dependent: :destroy
  accepts_nested_attributes_for :evaluations

  def build_evaluation(question)
    new_record? ? evaluations.build(question_id: question.id) : evaluations.find_by(question_id: question.id)
  end
  
  def quantitative_evaluations
    evaluations.select { |evaluation| evaluation.is_quantitative? }
  end

  def qualitative_evaluations
    evaluations.select { |evaluation| evaluation.is_qualitative? }
  end

  def final_score
    evaluations.sum(:score)
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :reviews
    belongs_to :event
    
    accepts_nested_attributes_for :questions, allow_destroy: true

    validates_presence_of :name
    validates_associated :questions
    validate :at_least_one_question
    validate :maximum_score_is_hundred

    def quantitative_questions
        questions.select { |question| question.is_quantitative? }
    end
    
    def maximum_score
        quantitative_questions.map{ |question| question.max_score }.sum
    end

    def safe_to_remove?
        reviews.count == 0
    end

    private 

    def at_least_one_question
        errors.add(:questions, "should be at least 1") if questions.size < 1
    end

    def maximum_score_is_hundred
        errors.add(:questions, "maximum scores should sum 100") if maximum_score != 100
    end
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  after_initialize :set_default_role, :if => :new_record?
  
  has_many :papers
  has_many :comments
  has_many :reviews

  paginates_per 6
  
  enum role: [:estudiante, :docente, :director]


  def login
    @login || self.username || self.email
  end

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def set_default_role
    self.role ||= :estudiante
  end

  def complete_name
    "#{name} #{lastname}"
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
  

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
    def fields_of_question(question_type)
        type = question_type
        type.slice!('Questions::')
        'questions/' + type.underscore + '_fields'
    end

    def question_types_info
        Question.subclasses.map { |question_type|
            [question_type.display_type, question_type] 
        }
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_director.html.erb
<nav class="nav-cato">
      <div class="container">
          <div class="nav-wrapper">
              <ul class="right hide-on-med-and-down">
                  <li>
                      <a href="#!" class="dropdown-trigger" data-target="dropdown2">
                          <%= current_user.name %> <%= current_user.lastname %>
                          <em class="material-icons right">arrow_drop_down</em>
                      </a>
                  </li>
              </ul>
              <ul id="nav-mobile" class="left hide-on-med-and-down">
                  <li><%= link_to "Eventos", events_path %></li>
                  <li>
                    <a href="#!" class="dropdown-trigger" data-target="users-drop">
                        Usuarios
                        <em class="material-icons right">arrow_drop_down</em>
                    </a>
                  </li>
                  <li><a href="/documents">Documentos</a></li>
              </ul>
          </div>
      </div>
  </nav>

<ul id="dropdown2" class="dropdown-content">
    <li>
        <%= link_to 'Modificar mis datos', edit_user_registration_path %>
    </li>
    <li><a href="/users/change_password">Cambiar contraseña</a></li>
    <li class="divider"></li>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
          Salir
          <em class="material-icons right">directions_run</em>
      <% end %>
    </li>
</ul>

<ul id="users-drop" class="dropdown-content">
    <li><%= link_to "Lista de usuarios", users_path %></li>
    <li><%= link_to "Crear usuario", new_user_path %></li>
</ul>

app/views/layouts/_director_professor.html.erb
<nav class="nav-cato">
      <div class="container">
          <div class="nav-wrapper">
              <ul class="right hide-on-med-and-down">
                  <li>
                      <a href="#!" class="dropdown-trigger" data-target="dropdown2">
                          <%= current_user.name %> <%= current_user.lastname %>
                          <em class="material-icons right">arrow_drop_down</em>
                      </a>
                  </li>
              </ul>
              <ul id="nav-mobile" class="left hide-on-med-and-down">
                  <li>
                    <a href="#!" class="dropdown-trigger" data-target="events-drop">
                        Eventos
                        <em class="material-icons right">arrow_drop_down</em>
                    </a>
                  </li>
                  <li>
                    <a href="#!" class="dropdown-trigger" data-target="users-drop">
                        Usuarios
                        <em class="material-icons right">arrow_drop_down</em>
                    </a>
                  </li>
                  <li><a href="/documents">Documentos</a></li>
              </ul>
          </div>
      </div>
  </nav>

<ul id="dropdown2" class="dropdown-content">
    <li>
        <%= link_to 'Modificar mis datos', edit_user_registration_path %>
    </li>
    <li><a href="/users/change_password">Cambiar contraseña</a></li>
    <li class="divider"></li>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
          Salir
          <em class="material-icons right">directions_run</em>
      <% end %>
    </li>
</ul>

<ul id="events-drop" class="dropdown-content">
    <li><%= link_to "Lista de eventos", events_path %></li>
    <li><%= link_to "Crear evento", new_event_path %></li>
</ul>
<ul id="users-drop" class="dropdown-content">
    <li><%= link_to "Lista de usuarios", users_path %></li>
    <li><%= link_to "Crear usuario", new_user_path %></li>
</ul>

app/views/layouts/_header.html.erb
<% if current_user && current_user.estudiante? %>
    <%= render 'layouts/student' %><br>
<% end %>

<% if current_user && current_user.professor_role? %>
  <%= render 'layouts/director_professor' %><br>
<% elsif current_user && current_user.admin_role? %>
  <%= render 'layouts/professor_admin' %><br>
<% elsif current_user && current_user.docente? %>
  <%= render 'layouts/professor' %><br>
<% elsif current_user && current_user.director? %>
  <%= render 'layouts/director' %><br>
<% end %>

app/views/layouts/_professor.html.erb
<nav class="nav-cato">
    <div class="container">
        <div class="nav-wrapper">
            <ul class="right hide-on-med-and-down">
                <li>
                      <a href="#!" class="dropdown-trigger" data-target="dropdown2">
                          <%= current_user.name %> <%= current_user.lastname %>
                          <em class="material-icons right">arrow_drop_down</em>
                      </a>
                  </li>
            </ul>

            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="/events">Eventos</a></li>
                <li>
                    <a href="#!" class="dropdown-trigger" data-target="docs-drop">
                        Documentos
                        <em class="material-icons right">arrow_drop_down</em>
                    </a>
                  </li>
            </ul>
        </div>
    </div>
</nav>

<ul id="dropdown2" class="dropdown-content">
    <li>
        <%= link_to 'Modificar mis datos', edit_user_registration_path %>
    </li>
    <li><a href="/users/change_password">Cambiar contraseña</a></li>
    <li class="divider"></li>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
          Salir
          <em class="material-icons right">directions_run</em>
      <% end %>
    </li>
</ul>
<ul id="docs-drop" class="dropdown-content">
    <li><a href="/assigned_tutor">Documentos asignados como tutor</a></li>
    <li><a href="/assigned_relator">Documentos asignados como relator</a></li>
</ul>

app/views/layouts/_professor_admin.html.erb
<nav class="nav-cato">
      <div class="container">
          <div class="nav-wrapper">
              <ul class="right hide-on-med-and-down">
                  <li>
                      <a href="#!" class="dropdown-trigger" data-target="dropdown2">
                          <%= current_user.name %> <%= current_user.lastname %>
                          <em class="material-icons right">arrow_drop_down</em>
                      </a>
                  </li>
              </ul>
              <ul id="nav-mobile" class="left hide-on-med-and-down">
                  <li>
                    <a href="#!" class="dropdown-trigger" data-target="events-drop">
                        Eventos
                        <em class="material-icons right">arrow_drop_down</em>
                    </a>
                  </li>
                  <li>
                    <a href="#!" class="dropdown-trigger" data-target="docs-drop">
                        Documentos
                        <em class="material-icons right">arrow_drop_down</em>
                    </a>
                  </li>
              </ul>
          </div>
      </div>
  </nav>

<ul id="dropdown2" class="dropdown-content">
    <li>
        <%= link_to 'Modificar mis datos', edit_user_registration_path %>
    </li>
    <li><a href="/users/change_password">Cambiar contraseña</a></li>
    <li class="divider"></li>
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
          Salir
          <em class="material-icons right">directions_run</em>
      <% end %>
    </li>
</ul>

<ul id="events-drop" class="dropdown-content">
    <li><%= link_to "Lista de eventos", events_path %></li>
    <li><%= link_to "Crear evento", new_event_path %></li>
</ul>
<ul id="docs-drop" class="dropdown-content">
    <li><a href="/documents">Lista documentos</a></li>
    <li><a href="/assigned_tutor">Documentos asignados como tutor</a></li>
    <li><a href="/assigned_relator">Documentos asignados como relator</a></li>
</ul>

app/views/layouts/_student.html.erb
<nav class="nav-cato">
        <div class="container">
            <div class="nav-wrapper">
                <ul class="right hide-on-med-and-down">
                    <li>
                        <a href="#!" class="dropdown-trigger" data-target="dropdown1">
                            <%= current_user.name %> <%= current_user.lastname %>
                            <em class="material-icons right">arrow_drop_down</em>
                        </a>
                    </li>
                </ul>
                <ul id="nav-mobile" class="left hide-on-med-and-down">
                    <li><a href="/events">Eventos</a></li>
                    <li><a href="/my_documents">Mis Documentos</a></li>
                </ul>
            </div>
        </div>
    </nav>

  <ul id="dropdown1" class="dropdown-content">
    <li>
        <%= link_to 'Modificar mis datos', edit_user_registration_path %>
    </li>
    <li><a href="/users/change_password">Cambiar contraseña</a></li>
    <li class="divider"></li>
    <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
            Salir
            <em class="material-icons right">directions_run</em>
        <% end %>
      </li>
  </ul>

app/views/layouts/acta.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Acta</title>
    <%= wicked_pdf_stylesheet_link_tag 'acta' %>
    <meta charset='utf-8'>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema de Revisión y Evaluación de Documentos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag asset_path('doc-reviewer.png'), :rel=>'icon', :type=>'image/png' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% unless flash.empty? %>
     <script type="text/javascript">
        <% flash.each do |f| %>
	        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
	     	  toastr['<%= type %>']('<%= f[1] %>');
	      <% end %>
     </script>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Pdf</title>
    <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
    <meta charset='utf-8'>
</head>
<body class="pdf-show">
    <%= yield %>
</body>
</html>